# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87e917aba69bbcf82815c0cdde3d06edf43d63362478e3221e661e2fafaaba883d3ffb4da4a8fc6bf271a8595ad3e8ba921a13027d1a16a912fdad8fb1f84e74

test:
  secret_key_base: 906b234c3b5808a3a0f0319abc047f4328b1557566c2032cfc4142177cbb99cee234a51086afb730a98358179c0dfc16b1473d67cc63e517243c0a0d4bb278ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
